name: "💡意见建议"
description: "提出你的好想法"
labels: [ "建议" ]
assignees: [ "ForteScarlet" ]
# https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
body:
  - type: markdown
    attributes:
      value: |
         ## 须知
         ### 确认
         在提出建议前，请确认以下内容：
         1. 我已参阅过相关文档、注释，并确认此建议是合理的。
         2. 我已确认 [issues](https://github.com/ForteScarlet/simpler-robot/issues) 没有类似/重复问题或建议。
         3. 我已确认所述内容不涉及任何个人隐私或其他敏感信息。
         
         ### 知悉
         请知悉以下内容：
         1. 当意见建议未被完全确认或等待发起者回复的情况下，发起者如果超过一周未作应答，则会视为「无效」并做关闭处理。
         2. 仅接受针对于框架本身的合理建议。被团队认定为不合理的建议将会被拒绝。
         3. 如果有能力，可以通过 [pr](https://github.com/ForteScarlet/simpler-robot/pulls) 向我们提供代码协助，非常感谢。
 
         <hr />
         
  - type: textarea
    id: advice
    attributes:
      label: 建议描述
      description: 描述你的建议
      placeholder: "例如: 我希望能够自动生成脑海中的需求"
    validations:
      required: true
