name: "🖼作品展示申请"
description: "展示你的作品～"
labels: [ "作品展示" ]
assignees: [ "ForteScarlet" ]
# https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
body:

  - type: textarea
    id: show
    attributes:
      label: 作品信息
      description: 提供你的作品以及相关信息，尽可能的详细，例如开发人员、仓库/网站地址、类型、简介、logo之类的。
      placeholder: "详细的作品信息"
    validations:
      required: true

