name: Publish Snapshot
on: # push
  push:
    branches:
      - v3-dev
      - v3-dev-snapshot**
      - v*.*.**
    paths:
      - '**src/**/kotlin/**.kt'
      - '**src/**/java/**.java'
      - 'buildSrc'

env:
  IS_CI: true
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SIMBOT_IS_SNAPSHOT: true
  SIMBOT_SNAPSHOT_ONLY: true
  GRADLE_OPTS: "-Xmx8g -Xms2g -Dfile.encoding=UTF-8"

jobs:
  publish-snapshot:
    name: Publish snapshot
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v3

      # setup Java
      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Run All Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: assemble allTests

      - name: Gradle publish snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: |
            publishToSonatype
            closeAndReleaseStagingRepository
            --info 
            --warning-mode all
            -x test
            --build-cache
            -Porg.gradle.jvmargs="-Dfile.encoding=UTF-8" 
            -Porg.gradle.workers.max=8 
            -Porg.gradle.parallel=true
            -Porg.gradle.daemon=false

# -Xmx8g -Xms2g -XX:MaxMetaspaceSize=1G

